version: "3.9"
services:
  reverse-proxy:
    image: traefik:latest
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  timetagger:
    image: ghcr.io/almarklein/timetagger:latest
    container_name: "timetagger"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timetagger.rule=Host(`timetagger.local.host`)"
      - "traefik.http.routers.timetagger.entrypoints=web"
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=${TIMETAGGER_CREDENTIALS}
    volumes:
      - ./timetagger:/root/_timetagger/
    ports:
      - "9999:80"

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.local.host`)"
      - "traefik.http.routers.excalidraw.entrypoints=web"
    ports:
      - "9998:80"
